#!/bin/bash

function up() {
	echo "Starting OrgBook BC demo"

	if ! [ -z "$ORGBOOK_HOST" ]; then
		DOCKER_ENV="ORGBOOK_HOST=${ORGBOOK_HOST}"
		export $DOCKER_ENV
	fi

	docker-compose -f ./docker/docker-compose.yaml up -d
	exit 0
}

function down() {
    echo "Shutting down OrgBook BC demo"
	docker-compose -f ./docker/docker-compose.yaml down
	exit 0
}

function display_help() {
	help="$(basename "$0") [up|down] [-h|--help]
1) up will start demo in detached mode.
	Example usage: ./run_demo up
2) down will stop demo and tear down containers
	Example usage: ./run_demo down
Options:
	-h|--help  Help"
	echo "$help"
}


shopt -s nocasematch

cd $(dirname $0)

for i in "$@"
do
	case $i in
	-h|--help)
		display_help
		exit 0
	;;
	up|down)
		DEMO=$i
	;;
	esac
done

if [ "$DEMO" = "up" ]; then
	up
elif [ "$DEMO" = "down" ]; then
	down
else
	display_help
	exit 1
fi